builds:
  - id: linux-binaries
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - '386'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}'
 
  - id: windows-binaries
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
      - arm64
      - '386'
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}.exe'
 
  - id: darwin-binaries
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
      - '386'
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}'

checksum:
  disable: true

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
