before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ incpatch .Version }}-next"

report_sizes: true

linux-builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - freebsd
    goarch:
      - amd64
      - arm64
      # - '386'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}'

windows-builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
      - arm64
      # - '386'
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}.exe'

checksum:
  disable: true

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
