builds:
  - env:
      - >-
        {{- if or (eq .Env.RUNNER_OS "macOS") (eq .Env.RUNNER_OS "Windows") -}}
          CGO_ENABLED=1
        {{- else -}}
          CGO_ENABLED=0
        {{- end -}}
    goos:
      # - windows
      # - darwin
      # - linux
      # - freebsd
      - >-
        {{- if (eq .Env.RUNNER_OS "macOS") -}}
          darwin
        {{- else if (eq .Env.RUNNER_OS "Windows") -}}
          windows
        {{- else -}}
          linux
        {{- end -}}
      - >-
        {{- if (eq .Env.RUNNER_OS "Linux") -}}
          freebsd
        {{- end -}}
    goarch:
      - amd64
      # - arm64
      # - '386'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}'
 
checksum:
  disable: true

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
