builds:
  - env:
      # - CGO_ENABLED={{ if eq .Os "windows"}}1{{else}}{{if eq .Os "darwin"}}1{{else}}0{{end}}{{end}}
      - CGO_ENABLED=0
    goos:
      # - windows
      # - darwin
      - linux
      # - freebsd
    goarch:
      - amd64
      # - arm64
      # - '386'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}'
 
checksum:
  disable: true

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
