before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ incpatch .Version }}-next"

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
      - '386'
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Runtime.Goos }}_checksums.txt'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
  name_template: "v{{ .Version }}"
