builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - '386'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/toshimaru/nyan/cmd.version={{.Version}}
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    overrides:
    - goos: darwin
      env:
        - CGO_ENABLED=1
    - goos: windows
      env:
        - CGO_ENABLED=1
checksum:
  disable: true

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
