name: Go Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      # - name: Build & Test
      #   run: |
      #     go build -v
      #     go test ./...
      
      # It only runs on Linux because the goreleaser command is executed on Linux.
      - name: Run GoReleaser
        # if: runner.os == 'linux' || runner.os == 'windows'
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean --snapshot --skip-publish
      
      # Output tests
      # - name: Normal Output Test
      #   run: go run main.go -- main.go

