name: Release darwin binaries
on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config .goreleaser-darwin.yml --clean --skip=announce,validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
